In [2]:
import pandas as pd
import numpy as np

In [4]:
pd.set_option('display.max_rows',500)
pd.set_option('display.max_columns',50)

In [5]:
# Reading the data
transaction = pd.read_excel('KPMG_VI_New_raw_data_update_final.xlsx',sheet_name='Transactions',skiprows=1)

In [7]:
# Looking first 10 rows
transaction.head(10)

,transaction_id,product_id,customer_id,transaction_date,online_order,order_status,brand,product_line,product_class,product_size,list_price,standard_cost,product_first_sold_date
0,1,2,2950,2017-02-25,0.0,Approved,Solex,Standard,medium,medium,71.49,53.62,41245.0
1,2,3,3120,2017-05-21,1.0,Approved,Trek Bicycles,Standard,medium,large,2091.47,388.92,41701.0
2,3,37,402,2017-10-16,0.0,Approved,OHM Cycles,Standard,low,medium,1793.43,248.82,36361.0
3,4,88,3135,2017-08-31,0.0,Approved,Norco Bicycles,Standard,medium,medium,1198.46,381.10,36145.0
4,5,78,787,2017-10-01,1.0,Approved,Giant Bicycles,Standard,medium,large,1765.30,709.48,42226.0
5,6,25,2339,2017-03-08,1.0,Approved,Giant Bicycles,Road,medium,medium,1538.99,829.65,39031.0
6,7,22,1542,2017-04-21,1.0,Approved,WeareA2B,Standard,medium,medium,60.34,45.26,34165.0
7,8,15,2459,2017-07-15,0.0,Approved,WeareA2B,Standard,medium,medium,1292.84,13.44,39915.0
8,9,67,1305,2017-08-10,0.0,Approved,Solex,Standard,medium,large,1071.23,380.74,33455.0
9,10,12,3262,2017-08-30,1.0,Approved,WeareA2B,Standard,medium,medium,1231.15,161.60,38216.0

In [8]:
# Looking bottom 5 rows
transaction.tail()

,transaction_id,product_id,customer_id,transaction_date,online_order,order_status,brand,product_line,product_class,product_size,list_price,standard_cost,product_first_sold_date
19995,19996,51,1018,2017-06-24,1.0,Approved,OHM Cycles,Standard,high,medium,2005.66,1203.40,37823.0
19996,19997,41,127,2017-11-09,1.0,Approved,Solex,Road,medium,medium,416.98,312.74,35560.0
19997,19998,87,2284,2017-04-14,1.0,Approved,OHM Cycles,Standard,medium,medium,1636.90,44.71,40410.0
19998,19999,6,2764,2017-07-03,0.0,Approved,OHM Cycles,Standard,high,medium,227.88,136.73,38216.0
19999,20000,11,1144,2017-09-22,1.0,Approved,Trek Bicycles,Standard,medium,small,1775.81,1580.47,36334.0

In [10]:
transaction.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   transaction_id           20000 non-null  int64
 1   product_id               20000 non-null  int64
 2   customer_id              20000 non-null  int64
 3   transaction_date         20000 non-null  datetime64[ns]
 4   online_order             19640 non-null  float64
 5   order_status             20000 non-null  object
 6   brand                    19803 non-null  object
 7   product_line             19803 non-null  object
 8   product_class            19803 non-null  object
 9   product_size             19803 non-null  object
 10  list_price               20000 non-null  float64
 11  standard_cost            19803 non-null  float64
 12  product_first_sold_date  19803 non-null  float64
dtypes: datetime64[ns](1), float64(4), int64(3), object(5)
memory usage: 2.0+ MB

In [15]:
# Checking the number of missing values in each column
pd.isnull(transaction).sum()

transaction_id               0
product_id                   0
customer_id                  0
transaction_date             0
online_order               360
order_status                 0
brand                      197
product_line               197
product_class              197
product_size               197
list_price                   0
standard_cost              197
product_first_sold_date    197
dtype: int64

In [16]:
transaction[transaction.brand.isnull()]

,transaction_id,product_id,customer_id,transaction_date,online_order,order_status,brand,product_line,product_class,product_size,list_price,standard_cost,product_first_sold_date
136,137,0,431,2017-09-23,0.0,Approved,NaN,NaN,NaN,NaN,1942.61,NaN,NaN
159,160,0,3300,2017-08-27,0.0,Approved,NaN,NaN,NaN,NaN,1656.86,NaN,NaN
366,367,0,1614,2017-03-10,0.0,Approved,NaN,NaN,NaN,NaN,850.89,NaN,NaN
406,407,0,2559,2017-06-14,1.0,Approved,NaN,NaN,NaN,NaN,710.59,NaN,NaN
676,677,0,2609,2017-07-02,0.0,Approved,NaN,NaN,NaN,NaN,1972.01,NaN,NaN
780,781,0,897,2017-05-10,1.0,Approved,NaN,NaN,NaN,NaN,311.54,NaN,NaN
1003,1004,0,2254,2017-05-16,0.0,Cancelled,NaN,NaN,NaN,NaN,205.84,NaN,NaN
1130,1131,0,2163,2017-03-09,0.0,Approved,NaN,NaN,NaN,NaN,605.54,NaN,NaN
1196,1197,0,2234,2017-04-04,0.0,Approved,NaN,NaN,NaN,NaN,756.31,NaN,NaN
1282,1283,0,397,2017-08-09,0.0,Approved,NaN,NaN,NaN,NaN,850.00,NaN,NaN
1653,1654,0,1972,2017-10-05,0.0,Approved,NaN,NaN,NaN,NaN,571.27,NaN,NaN
1680,1681,0,2733,2017-05-18,0.0,Approved,NaN,NaN,NaN,NaN,294.35,NaN,NaN
1752,1753,0,925,2017-07-25,0.0,Approved,NaN,NaN,NaN,NaN,149.30,NaN,NaN
1778,1779,0,2153,2017-03-23,0.0,Approved,NaN,NaN,NaN,NaN,447.25,NaN,NaN
2186,2187,0,1568,2017-03-14,1.0,Approved,NaN,NaN,NaN,NaN,1348.41,NaN,NaN
2302,2303,0,2465,2017-04-22,0.0,Approved,NaN,NaN,NaN,NaN,1021.43,NaN,NaN
2947,2948,0,3212,2017-09-14,0.0,Approved,NaN,NaN,NaN,NaN,1163.77,NaN,NaN
2990,2991,0,812,2017-04-10,1.0,Approved,NaN,NaN,NaN,NaN,1294.66,NaN,NaN
3194,3195,0,1902,2017-12-09,0.0,Approved,NaN,NaN,NaN,NaN,638.29,NaN,NaN
3259,3260,0,3168,2017-02-24,1.0,Approved,NaN,NaN,NaN,NaN,1202.34,NaN,NaN
3408,3409,0,52,2017-03-11,1.0,Approved,NaN,NaN,NaN,NaN,326.86,NaN,NaN
3781,3782,0,1503,2017-11-26,1.0,Approved,NaN,NaN,NaN,NaN,814.86,NaN,NaN
3877,3878,0,696,2017-07-30,0.0,Approved,NaN,NaN,NaN,NaN,1102.68,NaN,NaN
4024,4025,0,3264,2017-05-05,1.0,Approved,NaN,NaN,NaN,NaN,1880.40,NaN,NaN
4073,4074,0,1841,2017-04-09,0.0,Approved,NaN,NaN,NaN,NaN,1541.62,NaN,NaN
4127,4128,0,3242,2017-01-04,1.0,Approved,NaN,NaN,NaN,NaN,639.38,NaN,NaN
4222,4223,0,2479,2017-05-05,1.0,Approved,NaN,NaN,NaN,NaN,402.14,NaN,NaN
4224,4225,0,2405,2017-05-02,0.0,Approved,NaN,NaN,NaN,NaN,710.55,NaN,NaN
4227,4228,0,3464,2017-06-04,0.0,Approved,NaN,NaN,NaN,NaN,1142.89,NaN,NaN
4338,4339,0,1741,2017-04-12,0.0,Approved,NaN,NaN,NaN,NaN,813.60,NaN,NaN
4404,4405,0,325,2017-08-10,0.0,Approved,NaN,NaN,NaN,NaN,1833.17,NaN,NaN
4604,4605,0,1957,2017-05-01,0.0,Approved,NaN,NaN,NaN,NaN,1285.47,NaN,NaN
4652,4653,0,104,2017-03-08,0.0,Approved,NaN,NaN,NaN,NaN,1678.71,NaN,NaN
4713,4714,0,2454,2017-11-05,1.0,Approved,NaN,NaN,NaN,NaN,437.51,NaN,NaN
4832,4833,0,961,2017-09-03,0.0,Approved,NaN,NaN,NaN,NaN,366.22,NaN,NaN
4895,4896,0,922,2017-06-25,0.0,Approved,NaN,NaN,NaN,NaN,1199.26,NaN,NaN
4966,4967,0,2217,2017-08-16,1.0,Approved,NaN,NaN,NaN,NaN,1888.45,NaN,NaN
5064,5065,0,3399,2017-06-14,0.0,Approved,NaN,NaN,NaN,NaN,237.44,NaN,NaN
5158,5159,0,1418,2017-06-01,0.0,Approved,NaN,NaN,NaN,NaN,317.30,NaN,NaN
5206,5207,0,531,2017-03-02,1.0,Approved,NaN,NaN,NaN,NaN,1527.25,NaN,NaN
5260,5261,0,3322,2017-12-28,0.0,Approved,NaN,NaN,NaN,NaN,1563.94,NaN,NaN
5266,5267,0,1172,2017-10-05,0.0,Approved,NaN,NaN,NaN,NaN,1146.42,NaN,NaN
5602,5603,0,947,2017-06-15,0.0,Approved,NaN,NaN,NaN,NaN,1192.33,NaN,NaN
5861,5862,0,2404,2017-12-28,0.0,Approved,NaN,NaN,NaN,NaN,1672.07,NaN,NaN
6071,6072,0,2930,2017-03-01,1.0,Approved,NaN,NaN,NaN,NaN,1099.68,NaN,NaN
6137,6138,0,3145,2017-01-17,0.0,Approved,NaN,NaN,NaN,NaN,1281.60,NaN,NaN
6167,6168,0,1591,2017-11-15,1.0,Approved,NaN,NaN,NaN,NaN,1220.66,NaN,NaN
6250,6251,0,3102,2017-08-31,1.0,Approved,NaN,NaN,NaN,NaN,1061.92,NaN,NaN
6268,6269,0,2121,2017-01-10,0.0,Approved,NaN,NaN,NaN,NaN,1502.93,NaN,NaN
6418,6419,0,1707,2017-09-03,0.0,Approved,NaN,NaN,NaN,NaN,398.08,NaN,NaN
6429,6430,0,714,2017-10-16,1.0,Approved,NaN,NaN,NaN,NaN,101.55,NaN,NaN
6499,6500,0,1665,2017-07-20,0.0,Approved,NaN,NaN,NaN,NaN,1957.87,NaN,NaN
6595,6596,0,811,2017-01-27,1.0,Approved,NaN,NaN,NaN,NaN,1095.66,NaN,NaN
6643,6644,0,1319,2017-02-22,1.0,Approved,NaN,NaN,NaN,NaN,1776.08,NaN,NaN
6674,6675,0,1777,2017-09-08,0.0,Approved,NaN,NaN,NaN,NaN,752.36,NaN,NaN
6932,6933,0,913,2017-10-28,0.0,Approved,NaN,NaN,NaN,NaN,172.09,NaN,NaN
6960,6961,0,1760,2017-07-30,1.0,Approved,NaN,NaN,NaN,NaN,1740.16,NaN,NaN
6987,6988,0,1462,2017-05-06,0.0,Approved,NaN,NaN,NaN,NaN,1734.30,NaN,NaN
7015,7016,0,1238,2017-07-25,0.0,Approved,NaN,NaN,NaN,NaN,240.72,NaN,NaN
7046,7047,0,2758,2017-12-15,0.0,Approved,NaN,NaN,NaN,NaN,1958.34,NaN,NaN
7205,7206,0,2424,2017-01-26,1.0,Approved,NaN,NaN,NaN,NaN,330.36,NaN,NaN
7234,7235,0,2555,2017-12-19,1.0,Approved,NaN,NaN,NaN,NaN,1709.26,NaN,NaN
7355,7356,0,3358,2017-06-21,0.0,Approved,NaN,NaN,NaN,NaN,60.72,NaN,NaN
7609,7610,0,24,2017-05-11,0.0,Approved,NaN,NaN,NaN,NaN,1193.44,NaN,NaN
7694,7695,0,23,2017-04-02,1.0,Approved,NaN,NaN,NaN,NaN,2037.77,NaN,NaN
7729,7730,0,503,2017-05-30,1.0,Approved,NaN,NaN,NaN,NaN,1349.47,NaN,NaN
7734,7735,0,989,2017-09-29,0.0,Approved,NaN,NaN,NaN,NaN,56.21,NaN,NaN
7779,7780,0,1576,2017-01-25,1.0,Approved,NaN,NaN,NaN,NaN,126.36,NaN,NaN
7850,7851,0,2598,2017-04-27,0.0,Approved,NaN,NaN,NaN,NaN,1300.96,NaN,NaN
7948,7949,0,26,2017-09-08,0.0,Approved,NaN,NaN,NaN,NaN,1697.27,NaN,NaN
8159,8160,0,1075,2017-07-31,0.0,Approved,NaN,NaN,NaN,NaN,26.15,NaN,NaN
8215,8216,0,1729,2017-10-28,0.0,Approved,NaN,NaN,NaN,NaN,875.99,NaN,NaN
8297,8298,0,1204,2017-11-16,0.0,Approved,NaN,NaN,NaN,NaN,1862.82,NaN,NaN
8321,8322,0,1488,2017-11-12,0.0,Approved,NaN,NaN,NaN,NaN,2028.26,NaN,NaN
8328,8329,0,1920,2017-10-25,0.0,Approved,NaN,NaN,NaN,NaN,678.25,NaN,NaN
8423,8424,0,1343,2017-12-02,1.0,Approved,NaN,NaN,NaN,NaN,890.28,NaN,NaN
8485,8486,0,14,2017-08-16,1.0,Approved,NaN,NaN,NaN,NaN,1084.18,NaN,NaN
8526,8527,0,218,2017-03-26,1.0,Approved,NaN,NaN,NaN,NaN,1107.08,NaN,NaN
8585,8586,0,587,2017-10-31,1.0,Approved,NaN,NaN,NaN,NaN,1790.31,NaN,NaN
8609,8610,0,1479,2017-12-15,0.0,Approved,NaN,NaN,NaN,NaN,724.37,NaN,NaN
8610,8611,0,2553,2017-03-07,1.0,Approved,NaN,NaN,NaN,NaN,1095.65,NaN,NaN
8924,8925,0,719,2017-09-11,1.0,Approved,NaN,NaN,NaN,NaN,1223.24,NaN,NaN
8955,8956,0,2832,2017-06-20,1.0,Approved,NaN,NaN,NaN,NaN,541.44,NaN,NaN
9186,9187,0,2844,2017-10-22,0.0,Approved,NaN,NaN,NaN,NaN,470.07,NaN,NaN
9230,9231,0,3138,2017-02-25,0.0,Approved,NaN,NaN,NaN,NaN,2052.92,NaN,NaN
9275,9276,0,731,2017-07-15,1.0,Approved,NaN,NaN,NaN,NaN,1817.13,NaN,NaN
9325,9326,0,2310,2017-10-25,0.0,Approved,NaN,NaN,NaN,NaN,1473.09,NaN,NaN
9419,9420,0,1672,2017-11-13,1.0,Approved,NaN,NaN,NaN,NaN,1480.76,NaN,NaN
9453,9454,0,2764,2017-07-23,1.0,Approved,NaN,NaN,NaN,NaN,2012.84,NaN,NaN
9478,9479,0,778,2017-11-27,0.0,Approved,NaN,NaN,NaN,NaN,1711.35,NaN,NaN
9629,9630,0,2324,2017-03-15,0.0,Approved,NaN,NaN,NaN,NaN,753.76,NaN,NaN
9714,9715,0,1546,2017-10-14,0.0,Approved,NaN,NaN,NaN,NaN,840.02,NaN,NaN
9759,9760,0,2553,2017-07-23,1.0,Approved,NaN,NaN,NaN,NaN,1922.94,NaN,NaN
10001,10002,0,219,2017-04-13,0.0,Approved,NaN,NaN,NaN,NaN,1759.30,NaN,NaN
10044,10045,0,1944,2017-01-11,1.0,Approved,NaN,NaN,NaN,NaN,330.91,NaN,NaN
10540,10541,0,216,2017-02-15,0.0,Approved,NaN,NaN,NaN,NaN,1029.36,NaN,NaN
10895,10896,0,2278,2017-09-02,0.0,Approved,NaN,NaN,NaN,NaN,1487.80,NaN,NaN
10959,10960,0,151,2017-01-06,1.0,Approved,NaN,NaN,NaN,NaN,1624.69,NaN,NaN
11015,11016,0,2456,2017-05-12,NaN,Approved,NaN,NaN,NaN,NaN,1719.95,NaN,NaN
11115,11116,0,2342,2017-04-17,0.0,Approved,NaN,NaN,NaN,NaN,899.52,NaN,NaN
11218,11219,0,2201,2017-11-09,0.0,Approved,NaN,NaN,NaN,NaN,554.38,NaN,NaN
11392,11393,0,1773,2017-10-15,1.0,Approved,NaN,NaN,NaN,NaN,960.51,NaN,NaN
11517,11518,0,2755,2017-08-07,0.0,Approved,NaN,NaN,NaN,NaN,1978.64,NaN,NaN
11530,11531,0,154,2017-09-19,1.0,Approved,NaN,NaN,NaN,NaN,36.78,NaN,NaN
11548,11549,0,3086,2017-06-29,0.0,Approved,NaN,NaN,NaN,NaN,74.89,NaN,NaN
11833,11834,0,96,2017-09-05,1.0,Approved,NaN,NaN,NaN,NaN,1091.51,NaN,NaN
11842,11843,0,2034,2017-05-22,0.0,Approved,NaN,NaN,NaN,NaN,695.23,NaN,NaN
12021,12022,0,968,2017-04-27,0.0,Approved,NaN,NaN,NaN,NaN,1148.41,NaN,NaN
12071,12072,0,2638,2017-08-03,0.0,Approved,NaN,NaN,NaN,NaN,750.25,NaN,NaN
12138,12139,0,2762,2017-02-19,1.0,Approved,NaN,NaN,NaN,NaN,1997.68,NaN,NaN
12205,12206,0,2034,2017-11-08,0.0,Approved,NaN,NaN,NaN,NaN,1392.76,NaN,NaN
12322,12323,0,1898,2017-11-05,1.0,Approved,NaN,NaN,NaN,NaN,1294.37,NaN,NaN
12343,12344,0,72,2017-07-11,0.0,Approved,NaN,NaN,NaN,NaN,311.57,NaN,NaN
12346,12347,0,172,2017-08-08,1.0,Approved,NaN,NaN,NaN,NaN,899.92,NaN,NaN
12461,12462,0,870,2017-10-30,0.0,Approved,NaN,NaN,NaN,NaN,162.87,NaN,NaN
12816,12817,0,264,2017-07-23,1.0,Approved,NaN,NaN,NaN,NaN,1678.51,NaN,NaN
12869,12870,0,2858,2017-03-29,0.0,Approved,NaN,NaN,NaN,NaN,1703.18,NaN,NaN
12911,12912,0,2205,2017-01-31,1.0,Approved,NaN,NaN,NaN,NaN,675.28,NaN,NaN
12968,12969,0,234,2017-04-08,1.0,Approved,NaN,NaN,NaN,NaN,487.80,NaN,NaN
13010,13011,0,1492,2017-12-25,1.0,Approved,NaN,NaN,NaN,NaN,1292.13,NaN,NaN
13024,13025,0,507,2017-07-22,NaN,Approved,NaN,NaN,NaN,NaN,1578.52,NaN,NaN
13027,13028,0,255,2017-02-25,1.0,Approved,NaN,NaN,NaN,NaN,922.15,NaN,NaN
13140,13141,0,2255,2017-07-31,0.0,Approved,NaN,NaN,NaN,NaN,122.74,NaN,NaN
13343,13344,0,847,2017-01-28,1.0,Approved,NaN,NaN,NaN,NaN,435.66,NaN,NaN
13344,13345,0,1319,2017-03-24,0.0,Approved,NaN,NaN,NaN,NaN,1409.68,NaN,NaN
13368,13369,0,1010,2017-01-10,1.0,Approved,NaN,NaN,NaN,NaN,1315.16,NaN,NaN
13379,13380,0,1043,2017-08-22,1.0,Approved,NaN,NaN,NaN,NaN,1233.12,NaN,NaN
13459,13460,0,2015,2017-10-29,1.0,Approved,NaN,NaN,NaN,NaN,758.73,NaN,NaN
13519,13520,0,975,2017-05-19,1.0,Approved,NaN,NaN,NaN,NaN,405.94,NaN,NaN
13593,13594,0,298,2017-10-24,1.0,Approved,NaN,NaN,NaN,NaN,1026.70,NaN,NaN
13659,13660,0,3385,2017-03-18,1.0,Approved,NaN,NaN,NaN,NaN,687.90,NaN,NaN
13680,13681,0,764,2017-01-18,0.0,Approved,NaN,NaN,NaN,NaN,494.96,NaN,NaN
13719,13720,0,2702,2017-08-12,1.0,Approved,NaN,NaN,NaN,NaN,1181.89,NaN,NaN
13738,13739,0,3221,2017-03-17,1.0,Approved,NaN,NaN,NaN,NaN,465.71,NaN,NaN
13808,13809,0,1606,2017-10-22,0.0,Approved,NaN,NaN,NaN,NaN,880.30,NaN,NaN
13848,13849,0,1097,2017-10-15,0.0,Approved,NaN,NaN,NaN,NaN,1989.30,NaN,NaN
13872,13873,0,2341,2017-01-30,0.0,Approved,NaN,NaN,NaN,NaN,1413.98,NaN,NaN
14227,14228,0,1430,2017-08-06,0.0,Approved,NaN,NaN,NaN,NaN,483.12,NaN,NaN
14304,14305,0,1596,2017-06-30,1.0,Approved,NaN,NaN,NaN,NaN,753.01,NaN,NaN
14409,14410,0,1895,2017-10-06,0.0,Approved,NaN,NaN,NaN,NaN,883.91,NaN,NaN
14422,14423,0,417,2017-03-24,0.0,Approved,NaN,NaN,NaN,NaN,1216.40,NaN,NaN
14443,14444,0,2474,2017-11-29,0.0,Approved,NaN,NaN,NaN,NaN,32.44,NaN,NaN
14607,14608,0,2651,2017-03-07,1.0,Approved,NaN,NaN,NaN,NaN,16.08,NaN,NaN
14640,14641,0,1429,2017-02-23,0.0,Approved,NaN,NaN,NaN,NaN,1184.00,NaN,NaN
14754,14755,0,884,2017-07-07,0.0,Approved,NaN,NaN,NaN,NaN,1711.35,NaN,NaN
14835,14836,0,1738,2017-11-03,0.0,Approved,NaN,NaN,NaN,NaN,587.02,NaN,NaN
14845,14846,0,2192,2017-03-05,0.0,Approved,NaN,NaN,NaN,NaN,1919.23,NaN,NaN
14921,14922,0,448,2017-03-23,1.0,Approved,NaN,NaN,NaN,NaN,1660.68,NaN,NaN
15147,15148,0,3150,2017-04-26,0.0,Approved,NaN,NaN,NaN,NaN,1224.41,NaN,NaN
15267,15268,0,1830,2017-10-07,0.0,Approved,NaN,NaN,NaN,NaN,1535.84,NaN,NaN
15528,15529,0,3330,2017-08-07,1.0,Approved,NaN,NaN,NaN,NaN,150.51,NaN,NaN
15621,15622,0,289,2017-07-10,1.0,Approved,NaN,NaN,NaN,NaN,2062.95,NaN,NaN
15708,15709,0,1892,2017-03-24,1.0,Approved,NaN,NaN,NaN,NaN,1689.63,NaN,NaN
15927,15928,0,244,2017-03-01,1.0,Approved,NaN,NaN,NaN,NaN,1934.41,NaN,NaN
16002,16003,0,2747,2017-11-20,1.0,Approved,NaN,NaN,NaN,NaN,889.05,NaN,NaN
16009,16010,0,705,2017-06-25,0.0,Approved,NaN,NaN,NaN,NaN,1617.32,NaN,NaN
16032,16033,0,1481,2017-09-29,1.0,Approved,NaN,NaN,NaN,NaN,1788.93,NaN,NaN
16094,16095,0,10,2017-11-27,0.0,Approved,NaN,NaN,NaN,NaN,2064.08,NaN,NaN
16248,16249,0,467,2017-03-30,1.0,Approved,NaN,NaN,NaN,NaN,2020.14,NaN,NaN
16288,16289,0,2432,2017-05-18,0.0,Approved,NaN,NaN,NaN,NaN,489.58,NaN,NaN
16496,16497,0,243,2017-04-16,1.0,Approved,NaN,NaN,NaN,NaN,2076.81,NaN,NaN
16660,16661,0,1313,2017-10-04,1.0,Approved,NaN,NaN,NaN,NaN,2061.38,NaN,NaN
16681,16682,0,377,2017-03-11,0.0,Approved,NaN,NaN,NaN,NaN,877.44,NaN,NaN
16766,16767,0,1728,2017-06-14,0.0,Approved,NaN,NaN,NaN,NaN,1374.20,NaN,NaN
16906,16907,0,3421,2017-01-26,0.0,Approved,NaN,NaN,NaN,NaN,731.41,NaN,NaN
16934,16935,0,34,2017-02-14,0.0,Approved,NaN,NaN,NaN,NaN,1034.17,NaN,NaN
17149,17150,0,1091,2017-04-06,1.0,Approved,NaN,NaN,NaN,NaN,156.56,NaN,NaN
17235,17236,0,1026,2017-11-16,1.0,Approved,NaN,NaN,NaN,NaN,643.95,NaN,NaN
17291,17292,0,171,2017-05-30,1.0,Approved,NaN,NaN,NaN,NaN,517.53,NaN,NaN
17331,17332,0,1702,2017-02-20,1.0,Approved,NaN,NaN,NaN,NaN,226.94,NaN,NaN
17431,17432,0,2135,2017-08-15,1.0,Approved,NaN,NaN,NaN,NaN,1196.65,NaN,NaN
17534,17535,0,1210,2017-07-29,1.0,Approved,NaN,NaN,NaN,NaN,634.57,NaN,NaN
17767,17768,0,168,2017-03-13,0.0,Approved,NaN,NaN,NaN,NaN,1571.83,NaN,NaN
17918,17919,0,1295,2017-11-10,1.0,Approved,NaN,NaN,NaN,NaN,1999.54,NaN,NaN
17987,17988,0,2720,2017-03-11,0.0,Approved,NaN,NaN,NaN,NaN,1562.88,NaN,NaN
18021,18022,0,3104,2017-05-21,0.0,Approved,NaN,NaN,NaN,NaN,1150.59,NaN,NaN
18051,18052,0,918,2017-06-22,1.0,Approved,NaN,NaN,NaN,NaN,356.05,NaN,NaN
18244,18245,0,3261,2017-05-17,1.0,Approved,NaN,NaN,NaN,NaN,1780.22,NaN,NaN
18277,18278,0,586,2017-02-20,1.0,Approved,NaN,NaN,NaN,NaN,1438.90,NaN,NaN
18279,18280,0,916,2017-09-17,0.0,Approved,NaN,NaN,NaN,NaN,966.91,NaN,NaN
18344,18345,0,3359,2017-06-06,0.0,Approved,NaN,NaN,NaN,NaN,918.43,NaN,NaN
18492,18493,0,331,2017-02-17,1.0,Approved,NaN,NaN,NaN,NaN,1541.10,NaN,NaN
18543,18544,0,1078,2017-01-15,1.0,Approved,NaN,NaN,NaN,NaN,1476.88,NaN,NaN
18553,18554,0,1416,2017-10-24,1.0,Approved,NaN,NaN,NaN,NaN,1023.39,NaN,NaN
18778,18779,0,3355,2017-05-05,0.0,Approved,NaN,NaN,NaN,NaN,310.57,NaN,NaN
18819,18820,0,1503,2017-03-03,0.0,Approved,NaN,NaN,NaN,NaN,356.39,NaN,NaN
19017,19018,0,3384,2017-12-01,0.0,Approved,NaN,NaN,NaN,NaN,1695.42,NaN,NaN
19045,19046,0,2410,2017-11-02,1.0,Approved,NaN,NaN,NaN,NaN,877.60,NaN,NaN
19132,19133,0,181,2017-05-04,1.0,Approved,NaN,NaN,NaN,NaN,1401.63,NaN,NaN
19176,19177,0,1043,2017-06-06,0.0,Approved,NaN,NaN,NaN,NaN,2086.07,NaN,NaN
19196,19197,0,1182,2017-12-06,1.0,Approved,NaN,NaN,NaN,NaN,1761.75,NaN,NaN
19205,19206,0,2122,2017-01-04,1.0,Approved,NaN,NaN,NaN,NaN,1615.62,NaN,NaN
19340,19341,0,443,2017-12-26,1.0,Approved,NaN,NaN,NaN,NaN,744.54,NaN,NaN
19383,19384,0,2407,2017-06-11,0.0,Approved,NaN,NaN,NaN,NaN,1098.18,NaN,NaN
19793,19794,0,2860,2017-01-13,0.0,Approved,NaN,NaN,NaN,NaN,868.56,NaN,NaN
19859,19860,0,2468,2017-06-24,1.0,Approved,NaN,NaN,NaN,NaN,1497.43,NaN,NaN
19871,19872,0,61,2017-03-17,1.0,Approved,NaN,NaN,NaN,NaN,867.92,NaN,NaN

In [17]:
transaction= transaction[~transaction.brand.isnull()]

In [19]:
pd.isnull(transaction).sum()

transaction_id               0
product_id                   0
customer_id                  0
transaction_date             0
online_order               358
order_status                 0
brand                        0
product_line                 0
product_class                0
product_size                 0
list_price                   0
standard_cost                0
product_first_sold_date      0
dtype: int64

In [21]:
transaction.online_order.value_counts()

1.0    9739
0.0    9706
Name: online_order, dtype: int64

In [27]:
transaction= transaction[~transaction.online_order.isnull()]

In [28]:
pd.isnull(transaction).sum()

transaction_id             0
product_id                 0
customer_id                0
transaction_date           0
online_order               0
order_status               0
brand                      0
product_line               0
product_class              0
product_size               0
list_price                 0
standard_cost              0
product_first_sold_date    0
dtype: int64

In [30]:
transaction.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 19445 entries, 0 to 19999
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   transaction_id           19445 non-null  int64
 1   product_id               19445 non-null  int64
 2   customer_id              19445 non-null  int64
 3   transaction_date         19445 non-null  datetime64[ns]
 4   online_order             19445 non-null  float64
 5   order_status             19445 non-null  object
 6   brand                    19445 non-null  object
 7   product_line             19445 non-null  object
 8   product_class            19445 non-null  object
 9   product_size             19445 non-null  object
 10  list_price               19445 non-null  float64
 11  standard_cost            19445 non-null  float64
 12  product_first_sold_date  19445 non-null  float64
dtypes: datetime64[ns](1), float64(4), int64(3), object(5)
memory usage: 2.1+ MB

In [36]:
transaction['order_status'].value_counts().sort_values()

Cancelled      172
Approved     19273
Name: order_status, dtype: int64

In [38]:
transaction= transaction[transaction.order_status=='Approved']

In [40]:
transaction['brand'].value_counts().sort_values()

Norco Bicycles    2840
Trek Bicycles     2906
OHM Cycles        2967
WeareA2B          3215
Giant Bicycles    3217
Solex             4128
Name: brand, dtype: int64

In [41]:
transaction['product_line'].value_counts().sort_values()

Mountain      415
Touring      1204
Road         3859
Standard    13795
Name: product_line, dtype: int64

In [42]:
transaction['product_class'].value_counts().sort_values()

low        2888
high       2918
medium    13467
Name: product_class, dtype: int64

In [43]:
transaction['product_size'].value_counts().sort_values()

small      2752
large      3863
medium    12658
Name: product_size, dtype: int64

In [44]:
def to_date(num):
    startdate = "01/01/1900"
    date=[]
    for val in num:
        date.append(pd.to_datetime(startdate) + pd.DateOffset(days=int(val)))
    
    return pd.array(date)

In [45]:
transaction["Product_First_Sold_Date"] = to_date(transaction["product_first_sold_date"])

# Dropping the original column 
transaction.drop('product_first_sold_date',axis=1,inplace=True)
transaction.head()

,transaction_id,product_id,customer_id,transaction_date,online_order,order_status,brand,product_line,product_class,product_size,list_price,standard_cost,Product_First_Sold_Date
0,1,2,2950,2017-02-25,0.0,Approved,Solex,Standard,medium,medium,71.49,53.62,2012-12-04
1,2,3,3120,2017-05-21,1.0,Approved,Trek Bicycles,Standard,medium,large,2091.47,388.92,2014-03-05
2,3,37,402,2017-10-16,0.0,Approved,OHM Cycles,Standard,low,medium,1793.43,248.82,1999-07-22
3,4,88,3135,2017-08-31,0.0,Approved,Norco Bicycles,Standard,medium,medium,1198.46,381.10,1998-12-18
4,5,78,787,2017-10-01,1.0,Approved,Giant Bicycles,Standard,medium,large,1765.30,709.48,2015-08-12